export const GET_DEVICES = 'devices/GET_DEVICES';
export const GET_DEVICE_AVAILABILITY = 'devices/GET_DEVICE_AVAILABILITY';
export const GET_DEVICE_OPERABILITY = 'devices/GET_DEVICE_OPERABILITY';

export const SET_DEVICES = 'devices/SET_DEVICES';
export const SET_DEVICE_AVAILABILITY = 'devices/SET_DEVICE_AVAILABILITY';
export const SET_DEVICE_OPERABILITY = 'devices/SET_DEVICE_OPERABILITY';

export const FETCH_DEVICES = 'devices/FETCH_DEVICES';
export const FETCH_DEVICE_AVAILABILITY = 'devices/FETCH_DEVICE_AVAILABILITY';
export const FETCH_DEVICE_OPERABILITY  = 'devices/FETCH_DEVICE_OPERABILITY';
